apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ju8mh18a7-python-gitops
  description: This is GitOps manifest for ju8mh18a7-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ju8mh18a7-python
    backstage.io/kubernetes-id: ju8mh18a7-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ju8mh18a7-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ju8mh18a7-python
