apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ju8mh18a7-python
  janus-idp.io/tekton: ju8mh18a7-python
  backstage.io/kubernetes-id: ju8mh18a7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ju8mh18a7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
