apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ju8mh18a7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ju8mh18a7-python 
  name: ju8mh18a7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ju8mh18a7-python 
